src/objects/Device__c.object
<CustomObject>
    <fields>
        <fullName>Authenticated__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Authenticated</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>GUID__c</fullName>
        <externalId>true</externalId>
        <label>GUID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Health__c</fullName>
        <label>Health</label>
        <referenceTo>Health__c</referenceTo>
        <relationshipLabel>Devices</relationshipLabel>
        <relationshipName>Devices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Supports_Activity_Measures__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Supports Activity Measures</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Supports_Blood_Measures__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Supports Blood Measures</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Supports_Body_Measures__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Supports Body Measures</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Supports_Breath_Measures__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Supports Breath Measures</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Supports_Nutrition_Measures__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Supports Nutrition Measures</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Supports_Sleep_Measures__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Supports Sleep Measures</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>Device</label>
    <nameField>
        <displayFormat>Device-{0}</displayFormat>
        <label>Device Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Devices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Health__c.object
<CustomObject>
    <fields>
        <fullName>GUID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>GUID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Heroku_Registered__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Heroku Registered</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Health</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Weight__c</fullName>
        <label>Weight</label>
        <precision>4</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X2net_Registered__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Qualcomm 2net Guid - https://developer.qualcomm.com/mobile-development/create-connected-experiences/wireless-health-2net/2net-connect-api/authenticating-2net</description>
        <inlineHelpText>Is this user registered with Qualcomm 2net</inlineHelpText>
        <label>2net Registered</label>
        <type>Checkbox</type>
    </fields>
    <label>Health</label>
    <nameField>
        <label>Health Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Health</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Integration_Key__c.object
<CustomObject>
    <fields>
        <fullName>Secret__c</fullName>
        <label>Secret</label>
        <length>175</length>
        <maskChar>asterisk</maskChar>
        <maskType>all</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>key__c</fullName>
        <label>key</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Integration Key</label>
    <nameField>
        <label>Integration Keys Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Integration Keys</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Measurement__c.object
<CustomObject>
    <description>This is a generic template for Custom Object.  With this template, you may adjust the default elements and values and add new elements and values.</description>
    <fields>
        <fullName>Date_Time__c</fullName>
        <label>Date Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Device__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Device</label>
        <referenceTo>Device__c</referenceTo>
        <relationshipLabel>Measurements</relationshipLabel>
        <relationshipName>Measurements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Health__c</fullName>
        <label>Health</label>
        <referenceTo>Health__c</referenceTo>
        <relationshipLabel>Measurements</relationshipLabel>
        <relationshipName>Measurements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Weight__c</fullName>
        <label>Weight</label>
        <precision>13</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <label>Measurement</label>
    <nameField>
        <displayFormat>2Net-{0}</displayFormat>
        <label>Custom Object Label Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Measurements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/Security.cls
/* 
Copyright (c) 2014, salesforce.com, Inc.
All rights reserved.

Redistribution and use in source and binary forms, with or without modification, 
are permitted provided that the following conditions are met:

    * Redistributions of source code must retain the above copyright notice, 
    this list of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright notice, 
    this list of conditions and the following disclaimer in the documentation 
    and/or other materials provided with the distribution.
    * Neither the name of the salesforce.com, Inc. nor the names of its contributors 
    may be used to endorse or promote products derived from this software 
    without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND 
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED 
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. 
IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, 
INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, 
BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, 
DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF 
LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE 
OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED 
OF THE POSSIBILITY OF SUCH DAMAGE.

*/


public with sharing class Security {

    static public boolean Issue() {
        
        //returns true if the current user does not have enough FLS/CRUD
        //TODO:  Return the appropriate message depending on missing FLS or CRUD
        
        boolean toreturn=false;
        
        String [] integrationKeyFields = new String [] {'key__c','secret__c'};                              
        // Obtaining the field name/token map for the Contact object
        Map<String,Schema.SObjectField> m = Schema.SObjectType.Integration_key__c.fields.getMap();
        for (String fieldToCheck : integrationKeyFields) {
        // Check if the user has create access on the each field
            if (!m.get(fieldToCheck).getDescribe().isAccessible()           ) {
                toreturn=true;
            }
        }
        
        String [] deviceFields = new String [] {'type__c','guid__c','authenticated__c','supports_Body_Measures__c','supports_Blood_Measures__c',
           'supports_Activity_Measures__c','supports_Nutrition_Measures__c'
           ,'supports_Breath_Measures__c','Supports_Sleep_Measures__c'};
        
        // Obtaining the field name/token map for the Contact object
        m = Schema.SObjectType.device__c.fields.getMap();
        for (String fieldToCheck : deviceFields) {
        // Check if the user has create access on the each field
            if (!m.get(fieldToCheck).getDescribe().isAccessible() ||
          !m.get(fieldToCheck).getDescribe().isCreateable() ||
           !m.get(fieldToCheck).getDescribe().isUpdateable() 
            ) {
                toreturn=true;
            }
        }
        
        String [] healthFields = new String [] {'X2net_Registered__c','user__c','Heroku_Registered__c','guid__c'};
        
        // Obtaining the field name/token map for the Contact object
        m = Schema.SObjectType.health__c.fields.getMap();
        for (String fieldToCheck : healthFields) {
        // Check if the user has create access on the each field
            if (!m.get(fieldToCheck).getDescribe().isAccessible() ||
            !m.get(fieldToCheck).getDescribe().isCreateable() ||
            !m.get(fieldToCheck).getDescribe().isUpdateable() 
            ) {
                toreturn=true;
            }
        }
        

        
        
               String [] measureFields = new String [] {'health__c','Date_Time__c','Weight__c'};
        
        // Obtaining the field name/token map for the Health__c object
        m = Schema.SObjectType.Measurement__c.fields.getMap();
        for (String fieldToCheck : measureFields) {
        // Check if the user has create access on the each field
            if (!m.get(fieldToCheck).getDescribe().isAccessible()
            ) {
                toreturn=true;
            }
        }
        
        
        return toreturn;
    }


}